# Generated by Django 3.1.8 on 2023-10-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='receipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_receipe', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=2000)),
                ('calories', models.FloatField()),
                ('carbo', models.FloatField()),
                ('fat', models.FloatField()),
                ('protein', models.FloatField()),
            ],
        ),
    ]
