# Generated by Django 3.1.8 on 2023-10-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipes',
            name='name_receipe',
            field=models.CharField(max_length=200),
        ),
    ]
