# Generated by Django 3.1.8 on 2023-10-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_info', '0002_auto_20231012_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipes',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipes',
            name='carbo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipes',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipes',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
