# Generated by Django 3.1.8 on 2023-10-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritional_info', '0003_auto_20231012_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipes',
            old_name='description',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='receipes',
            name='tutorial',
            field=models.TextField(default='null', max_length=2000),
            preserve_default=False,
        ),
    ]
